name: langevin-agglomeration
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy<2.5
  - scipy
  - numba
  - matplotlib
  - pandas
  - h5py
  - pyyaml
  - pyvista
  - vtk<9.6
  - typer
  - rich
  - pytest
  - ruff
  - imageio
  - imageio-ffmpeg
  - pip
  - pip:
      - -e .
